//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsychologicalSupports.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassroomRelationship
    {
        public long ClassroomRelationshipsID { get; set; }
        public long StudentID { get; set; }
        public string IGS_Sishora { get; set; }
        public string Sociometry { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
