//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsychologicalSupports.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmotioTest
    {
        public long EmotioTestID { get; set; }
        public long StudentID { get; set; }
        public string PhysicalAggression { get; set; }
        public string IndirectAggression { get; set; }
        public string Irritability { get; set; }
        public string Negativism { get; set; }
        public string Touchiness { get; set; }
        public string Suspicion { get; set; }
        public string VerbalAggression { get; set; }
        public string Guilt { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
