//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsychologicalSupports.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interests_Card_50
    {
        public long Interests_Card_50ID { get; set; }
        public long StudentID { get; set; }
        public string PhysicsMathematics { get; set; }
        public string ChemistryBiology { get; set; }
        public string RadioEngineeringElectronics { get; set; }
        public string MechanicsDesign { get; set; }
        public string GeographyGeology { get; set; }
        public string LiteratureArt { get; set; }
        public string HistoryPolitics { get; set; }
        public string PedagogyMedicine { get; set; }
        public string EntrepreneurshiHomeEconomics { get; set; }
        public string SportsMilitary { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
