//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PsychologicalSupports.EF
{
    public partial class Self_esteem
    {
        public long Self_esteemID { get; set; }
        public long StudentID { get; set; }
        public string Indicator { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
