//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsychologicalSupports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AveragePoint
    {
        public long AveragePointID { get; set; }
        public Nullable<double> AveragePoint_6 { get; set; }
        public Nullable<double> AveragePoint_7 { get; set; }
        public Nullable<double> AveragePoint_8 { get; set; }
        public Nullable<double> AveragePoint_9 { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
