//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsychologicalSupports.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ClassTeacheInformation
    {
        [Key]
        [ForeignKey("Student")]
        public long StudentID { get; set; }
        [Display(Name = "Самовредительство")]
        public string Self_harmingBehavior { get; set; }
        [Display(Name = "Замкнутость")]
        public string Isolation { get; set; }
        [Display(Name = "Агрессия")]
        public string Aggression { get; set; }
        [Display(Name = "Избегание физического контакта")]
        public string AvoidPhysicalContact { get; set; }
        [Display(Name = "Боится идти домой")]
        public string AfraidToGoHome { get; set; }
        [Display(Name = "Убегает из дома")]
        public string RunningAwayFromHome { get; set; }
        [Display(Name = "Носит скрывающую одежду")]
        public string WearBodyHidingClothes { get; set; }
        [Display(Name = "Вызывающее поведение")]
        public string DefiantBehavior { get; set; }
        [Display(Name = "Низкая самооценка")]
        public string LowSelf_esteem { get; set; }
        [Display(Name = "Плохое отношение со сверстниками")]
        public string PoorPeerRelations { get; set; }
        [Display(Name = "Резкое изменения веса")]
        public string SharpWeightChange { get; set; }
        [Display(Name = "Эмоциональная неуравновешенность")]
        public string HystericalEmotionalImbalance { get; set; }
        [Display(Name = "ИСключительно хорошие знания о сексе")]
        public string ExceptionallyGoodSexKnowledge { get; set; }

        public virtual Student Student { get; set; }
    }
}
