//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsychologicalSupports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassTeacheInformation
    {
        public long ClassTeacheInformationID { get; set; }
        public long StudentID { get; set; }
        public string Self_harmingBehavior { get; set; }
        public string Isolation { get; set; }
        public string Aggression { get; set; }
        public string AvoidPhysicalContact { get; set; }
        public string AfraidToGoHome { get; set; }
        public string RunningAwayFromHome { get; set; }
        public string WearBodyHidingClothes { get; set; }
        public string DefiantBehavior { get; set; }
        public string LowSelf_esteem { get; set; }
        public string PoorPeerRelations { get; set; }
        public string SharpWeightChange { get; set; }
        public string HystericalEmotionalImbalance { get; set; }
        public string ExceptionallyGoodSexKnowledge { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
