//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsychologicalSupports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmotioTest
    {
        public long StudentID { get; set; }
        public byte PhysicalAggression { get; set; }
        public byte IndirectAggression { get; set; }
        public byte Irritability { get; set; }
        public byte Negativism { get; set; }
        public byte Touchiness { get; set; }
        public byte Suspicion { get; set; }
        public byte VerbalAggression { get; set; }
        public byte Guilt { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
