//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsychologicalSupports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterestsInSchoolSubject
    {
        public long StudentID { get; set; }
        public byte Russian { get; set; }
        public byte Belorussian { get; set; }
        public byte Physics { get; set; }
        public byte Story { get; set; }
        public byte SocialScientist { get; set; }
        public byte Biology { get; set; }
        public byte Chemistry { get; set; }
        public byte ComputerScience { get; set; }
        public byte English { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
