//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsychologicalSupports.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Карта интересов  145")]
    public partial class Interests_Card_145
    {
        [key]
        public long StudentID { get; set; }

        [Display(Name = "Билогия")]
        public string Biology { get; set; }
        [Display(Name = "География")]
        public string Geography { get; set; }
        [Display(Name = "Геология")]
        public string Geology { get; set; }
        [Display(Name = "Медицина")]
        public string TheMedicine { get; set; }
        [Display(Name = "Легкая и пищевая промышленность")]
        public string LightAndFoodIndustry { get; set; }
        [Display(Name = "Физика")]
        public string Physics { get; set; }
        [Display(Name = "Химия")]
        public string Chemistry { get; set; }
        [Display(Name = "Техника,механика")]
        public string EngineeringMechanics { get; set; }
        [Display(Name = "Электротехника")]
        public string ElectricalEngineeringRadioEngineering { get; set; }
        [Display(Name = "Обработка материалов")]
        public string MaterialHandling { get; set; }
        [Display(Name = "IT")]
        public string InformationTechnology { get; set; }
        [Display(Name = "Психология")]
        public string Psychology { get; set; }
        [Display(Name = "Строительство")]
        public string Building { get; set; }
        [Display(Name = "Транспорт")]
        public string Tranport { get; set; }
        [Display(Name = "Военные")]
        public string MilitarySpecialties { get; set; }
        [Display(Name = "История")]
        public string Story { get; set; }
        [Display(Name = "Литература")]
        public string Literature { get; set; }
        [Display(Name = "Жарналистика")]
        public string Journalism { get; set; }
        [Display(Name = "Социология")]
        public string Sociology { get; set; }
        [Display(Name = "Педагогика")]
        public string Pedagogy { get; set; }
        [Display(Name = "Право")]
        public string Right { get; set; }
        [Display(Name = "Сфера обслуживания")]
        public string ServiceSector { get; set; }
        [Display(Name = "Математика")]
        public string Maths { get; set; }
        [Display(Name = "Экономика")]
        public string Economy { get; set; }
        [Display(Name = "Лингвистика")]
        public string ForeignLanguages { get; set; }
        [Display(Name = "Исскуство")]
        public string Art { get; set; }
        [Display(Name = "Музыка")]
        public string Music { get; set; }
        [Display(Name = "Спорт")]
        public string Sport { get; set; }

        public virtual Student Student { get; set; }
    }
}
