//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsychologicalSupports.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("8 класс")]
    public partial class Intellectual_8_Class
    {
        [key]
        public long StudentID { get; set; }

        [Display(Name = "Карта интересов")]
        public string InterestMap { get; set; }

        [Display(Name = "Рекомендуемый профиль")]
        public string RecommendedProfile { get; set; }

        public virtual Student Student { get; set; }
    }
}
