//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsychologicalSupports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interests_Card_50
    {
        public long StudentID { get; set; }
        public byte PhysicsMathematics { get; set; }
        public byte ChemistryBiology { get; set; }
        public byte RadioEngineeringElectronics { get; set; }
        public byte MechanicsDesign { get; set; }
        public byte GeographyGeology { get; set; }
        public byte LiteratureArt { get; set; }
        public byte HistoryPolitics { get; set; }
        public byte PedagogyMedicine { get; set; }
        public byte EntrepreneurshiHomeEconomics { get; set; }
        public byte SportsMilitary { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
