//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsychologicalSupports.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Interests_Card_145
    {
        [Key]
        [ForeignKey("Student")]
        [Display(Name = "Номер учащегося")]
        public long StudentID { get; set; }

        [Display(Name = "Билогия")]
        public byte Biology { get; set; }
        [Display(Name = "География")]
        public byte Geography { get; set; }
        [Display(Name = "Геология")]
        public byte Geology { get; set; }
        [Display(Name = "Медицина")]
        public byte TheMedicine { get; set; }
        [Display(Name = "Легкая и пищевая промышленность")]
        public byte LightAndFoodIndustry { get; set; }
        [Display(Name = "Физика")]
        public byte Physics { get; set; }
        [Display(Name = "Химия")]
        public byte Chemistry { get; set; }
        [Display(Name = "Техника,механика")]
        public byte EngineeringMechanics { get; set; }
        [Display(Name = "Электротехника")]
        public byte ElectricalEngineeringRadioEngineering { get; set; }
        [Display(Name = "Обработка материалов")]
        public byte MaterialHandling { get; set; }
        [Display(Name = "IT")]
        public byte InformationTechnology { get; set; }
        [Display(Name = "Психология")]
        public byte Psychology { get; set; }
        [Display(Name = "Строительство")]
        public byte Building { get; set; }
        [Display(Name = "Транспорт")]
        public byte Tranport { get; set; }
        [Display(Name = "Военные")]
        public byte MilitarySpecialties { get; set; }
        [Display(Name = "История")]
        public byte Story { get; set; }
        [Display(Name = "Литература")]
        public byte Literature { get; set; }
        [Display(Name = "Жарналистика")]
        public byte Journalism { get; set; }
        [Display(Name = "Социология")]
        public byte Sociology { get; set; }
        [Display(Name = "Педагогика")]
        public byte Pedagogy { get; set; }
        [Display(Name = "Право")]
        public byte Right { get; set; }
        [Display(Name = "Сфера обслуживания")]
        public byte ServiceSector { get; set; }
        [Display(Name = "Математика")]
        public byte Maths { get; set; }
        [Display(Name = "Экономика")]
        public byte Economy { get; set; }
        [Display(Name = "Лингвистика")]
        public byte ForeignLanguages { get; set; }
        [Display(Name = "Исскуство")]
        public byte Art { get; set; }
        [Display(Name = "Музыка")]
        public byte Music { get; set; }
        [Display(Name = "Спорт")]
        public byte Sport { get; set; }

        public virtual Student Student { get; set; }
    }
}
