//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsychologicalSupports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intellectual_9_Class
    {
        public long Intellectual_9_ClassID { get; set; }
        public string Profile { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
