//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsychologicalSupports.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Intellectual_7_Class
    {
        [Key]
        [ForeignKey("Student")]
        public long StudentID { get; set; }
        [Display(Name = "IQ")]
        public string IQ { get; set; }
        [Display(Name = "Уровень")]
        public string Level { get; set; }
        [Display(Name = "Средний балл")]
        public Nullable<double> AveragePointСommon { get; set; }
        [Display(Name = "Средний балл по математике")]
        public Nullable<double> AveragePointMath { get; set; }

        public virtual Student Student { get; set; }
    }
}
