//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsychologicalSupports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterestsInSchoolSubject
    {
        public long StudentID { get; set; }
        public string Russian { get; set; }
        public string Belorussian { get; set; }
        public string Physics { get; set; }
        public string Story { get; set; }
        public string SocialScientist { get; set; }
        public string Biology { get; set; }
        public string Chemistry { get; set; }
        public string ComputerScience { get; set; }
        public string English { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
