//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsychologicalSupports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaAnxietyScale
    {
        public long StudentID { get; set; }
        public string School { get; set; }
        public string Interpersonal { get; set; }
        public string Self_assessment { get; set; }
        public string General { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
