//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsychologicalSupports.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Личностный тест Айзенко")]
    public partial class PersonalProtagonistAizenko
    {
        [key]
        public long StudentID { get; set; }
        [Display(Name = "Темперамент")]
        public string Temperament { get; set; }

        [Display(Name = "Тип")]
        public string Type { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
