//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsychologicalSupports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolMotivation
    {
        public long SchoolMotivationID { get; set; }
        public string StudyInClass { get; set; }
        public string TestFamilyStudiesLevel { get; set; }
        public string CognitiveInterest { get; set; }
        public string TesMotivationAchievementstLevel { get; set; }
        public string Classmates { get; set; }
        public string Pedagogues { get; set; }
        public string ByParents { get; set; }
        public string FromTheSideOfTheSchool { get; set; }
        public string FromTheSideOfTheFamily { get; set; }
        public string AwarenessOfSocialNecessity { get; set; }
        public string CommunicationMotif { get; set; }
        public string ExtracurricularSchoolMotivation { get; set; }
        public string TheMotiveOfSelf_Realization { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
